2023-10-17 21:34:46,658 INFO    StreamThr :15321 [internal.py:wandb_internal():86] W&B internal server running at pid: 15321, started at: 2023-10-17 21:34:46.657447
2023-10-17 21:34:46,659 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status
2023-10-17 21:34:46,663 INFO    WriterThread:15321 [datastore.py:open_for_write():85] open: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/run-wv7rm33y.wandb
2023-10-17 21:34:46,664 DEBUG   SenderThread:15321 [sender.py:send():369] send: header
2023-10-17 21:34:46,671 DEBUG   SenderThread:15321 [sender.py:send():369] send: run
2023-10-17 21:34:47,449 INFO    SenderThread:15321 [dir_watcher.py:__init__():211] watching files in: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files
2023-10-17 21:34:47,449 INFO    SenderThread:15321 [sender.py:_start_run_threads():1100] run started: wv7rm33y with start time 1697592886.657011
2023-10-17 21:34:47,453 DEBUG   SenderThread:15321 [sender.py:send_request():396] send_request: summary_record
2023-10-17 21:34:47,453 INFO    SenderThread:15321 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-10-17 21:34:47,461 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: check_version
2023-10-17 21:34:47,462 DEBUG   SenderThread:15321 [sender.py:send_request():396] send_request: check_version
2023-10-17 21:34:47,551 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: run_start
2023-10-17 21:34:47,554 DEBUG   HandlerThread:15321 [system_info.py:__init__():31] System info init
2023-10-17 21:34:47,554 DEBUG   HandlerThread:15321 [system_info.py:__init__():46] System info init done
2023-10-17 21:34:47,554 INFO    HandlerThread:15321 [system_monitor.py:start():181] Starting system monitor
2023-10-17 21:34:47,555 INFO    SystemMonitor:15321 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-10-17 21:34:47,556 INFO    HandlerThread:15321 [system_monitor.py:probe():201] Collecting system info
2023-10-17 21:34:47,557 INFO    SystemMonitor:15321 [interfaces.py:start():190] Started cpu monitoring
2023-10-17 21:34:47,559 INFO    SystemMonitor:15321 [interfaces.py:start():190] Started disk monitoring
2023-10-17 21:34:47,561 INFO    SystemMonitor:15321 [interfaces.py:start():190] Started gpu monitoring
2023-10-17 21:34:47,566 INFO    SystemMonitor:15321 [interfaces.py:start():190] Started memory monitoring
2023-10-17 21:34:47,572 INFO    SystemMonitor:15321 [interfaces.py:start():190] Started network monitoring
2023-10-17 21:34:47,579 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:34:47,582 DEBUG   HandlerThread:15321 [system_info.py:probe():195] Probing system
2023-10-17 21:34:47,586 DEBUG   HandlerThread:15321 [system_info.py:_probe_git():180] Probing git
2023-10-17 21:34:47,597 DEBUG   HandlerThread:15321 [system_info.py:_probe_git():188] Probing git done
2023-10-17 21:34:47,597 DEBUG   HandlerThread:15321 [system_info.py:probe():240] Probing system done
2023-10-17 21:34:47,597 DEBUG   HandlerThread:15321 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-32-generic-x86_64-with-glibc2.35', 'python': '3.9.17', 'heartbeatAt': '2023-10-18T01:34:47.582233', 'startedAt': '2023-10-18T01:34:46.647638', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/train_multi_knolling.py', 'codePath': 'train_multi_knolling_zzz/train_multi_knolling.py', 'git': {'remote': 'https://github.com/H-Y-H-Y-H/knolling_bot.git', 'commit': '036a12c034f2b51fc85d2dd043afb317bcdbea78'}, 'email': '552310797@qq.com', 'root': '/home/zhizhuo/Creative_Machines_Lab/knolling_bot', 'host': 'zhizhuo-Alienware-x15-R1', 'username': 'zhizhuo', 'executable': '/home/zhizhuo/anaconda3/envs/knolling/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 1149.2323749999998, 'min': 800.0, 'max': 4600.0}, 'cpu_freq_per_core': [{'current': 869.465, 'min': 800.0, 'max': 4600.0}, {'current': 2911.827, 'min': 800.0, 'max': 4600.0}, {'current': 2300.0, 'min': 800.0, 'max': 4600.0}, {'current': 1240.909, 'min': 800.0, 'max': 4600.0}, {'current': 1776.191, 'min': 800.0, 'max': 4600.0}, {'current': 939.231, 'min': 800.0, 'max': 4600.0}, {'current': 890.383, 'min': 800.0, 'max': 4600.0}, {'current': 2300.0, 'min': 800.0, 'max': 4600.0}, {'current': 973.381, 'min': 800.0, 'max': 4600.0}, {'current': 1832.637, 'min': 800.0, 'max': 4600.0}, {'current': 946.237, 'min': 800.0, 'max': 4600.0}, {'current': 2554.202, 'min': 800.0, 'max': 4600.0}, {'current': 1215.401, 'min': 800.0, 'max': 4600.0}, {'current': 899.561, 'min': 800.0, 'max': 4600.0}, {'current': 1663.178, 'min': 800.0, 'max': 4600.0}, {'current': 1835.202, 'min': 800.0, 'max': 4600.0}], 'disk': {'total': 388.0163116455078, 'used': 190.54202270507812}, 'gpu': 'NVIDIA GeForce RTX 3070 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3070 Laptop GPU', 'memory_total': 8370061312}], 'memory': {'total': 15.29227066040039}}
2023-10-17 21:34:47,597 INFO    HandlerThread:15321 [system_monitor.py:probe():211] Finished collecting system info
2023-10-17 21:34:47,597 INFO    HandlerThread:15321 [system_monitor.py:probe():214] Publishing system info
2023-10-17 21:34:47,597 DEBUG   HandlerThread:15321 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-10-17 21:34:47,598 DEBUG   HandlerThread:15321 [system_info.py:_save_pip():67] Saving pip packages done
2023-10-17 21:34:47,598 DEBUG   HandlerThread:15321 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-10-17 21:34:48,454 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/conda-environment.yaml
2023-10-17 21:34:48,454 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/wandb-summary.json
2023-10-17 21:34:48,454 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/requirements.txt
2023-10-17 21:34:48,884 DEBUG   HandlerThread:15321 [system_info.py:_save_conda():86] Saving conda packages done
2023-10-17 21:34:48,891 INFO    HandlerThread:15321 [system_monitor.py:probe():216] Finished publishing system info
2023-10-17 21:34:48,895 DEBUG   SenderThread:15321 [sender.py:send():369] send: files
2023-10-17 21:34:48,895 INFO    SenderThread:15321 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-10-17 21:34:48,904 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: stop_status
2023-10-17 21:34:48,906 DEBUG   SenderThread:15321 [sender.py:send_request():396] send_request: stop_status
2023-10-17 21:34:49,164 DEBUG   SenderThread:15321 [sender.py:send():369] send: telemetry
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: telemetry
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,165 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,166 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,167 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:49,253 INFO    wandb-upload_0:15321 [upload_job.py:push():133] Uploaded file /tmp/tmpk7h408h8wandb/tjcho9ay-wandb-metadata.json
2023-10-17 21:34:49,450 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/conda-environment.yaml
2023-10-17 21:34:49,451 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/output.log
2023-10-17 21:34:49,451 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/wandb-metadata.json
2023-10-17 21:34:49,586 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:34:51,451 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/output.log
2023-10-17 21:34:51,589 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:34:51,729 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status_report
2023-10-17 21:34:52,460 DEBUG   SenderThread:15321 [sender.py:send():369] send: config
2023-10-17 21:34:53,452 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/output.log
2023-10-17 21:34:53,591 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:34:54,453 INFO    Thread-16 :15321 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/files/output.log
2023-10-17 21:34:55,594 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:34:57,461 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status_report
2023-10-17 21:34:57,600 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:34:59,603 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:01,606 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:02,462 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status_report
2023-10-17 21:35:03,609 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:03,903 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: stop_status
2023-10-17 21:35:03,904 DEBUG   SenderThread:15321 [sender.py:send_request():396] send_request: stop_status
2023-10-17 21:35:05,611 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:07,618 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:08,069 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status_report
2023-10-17 21:35:09,622 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:11,625 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:13,071 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status_report
2023-10-17 21:35:13,629 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:15,638 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:17,676 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:18,078 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: status_report
2023-10-17 21:35:18,180 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:35:18,180 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:35:18,907 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: stop_status
2023-10-17 21:35:19,554 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:35:19,554 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:35:19,680 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:21,685 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:21,788 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:35:21,789 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:35:21,789 INFO    SenderThread:15321 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 321, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-10-17 21:35:23,687 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:23,907 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:25,694 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:26,802 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:35:26,803 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:35:27,698 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:28,908 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:29,701 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:31,705 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:33,714 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:33,911 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:34,944 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:35:34,944 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:35:35,718 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:37,722 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:38,913 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:39,728 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:41,733 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:43,739 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:43,915 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:45,746 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:47,574 DEBUG   SystemMonitor:15321 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-10-17 21:35:47,786 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:48,917 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:49,790 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:51,795 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:53,134 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:35:53,135 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:35:53,798 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:53,919 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:55,804 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:57,808 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:35:58,921 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:35:59,812 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:01,820 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:03,824 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:03,923 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:05,827 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:07,832 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:08,925 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:09,838 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:11,843 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:13,849 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:13,926 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:15,856 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:17,891 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:18,929 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:19,896 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:21,900 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:23,907 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:23,930 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:25,914 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:27,918 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:28,822 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:36:28,822 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:36:28,933 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:29,921 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:31,924 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:33,930 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:33,934 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:35,934 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:37,938 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:38,936 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:39,941 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:41,947 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:43,936 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:43,949 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:45,951 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:47,987 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:48,938 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:49,991 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:51,995 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:53,939 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:36:53,998 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:56,003 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:58,006 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:36:58,941 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:00,011 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:02,013 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:03,943 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:04,020 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:06,024 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:08,028 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:08,945 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:10,032 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:12,037 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:13,949 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:14,042 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:16,047 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:18,096 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:18,949 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:20,104 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:22,110 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:23,951 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:24,116 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:26,119 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:28,123 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:28,952 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:30,127 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:32,133 ERROR   gpu       :15321 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-10-17 21:37:33,419 ERROR   SenderThread:15321 [internal_api.py:execute():324] 409 response executing GraphQL.
2023-10-17 21:37:33,419 ERROR   SenderThread:15321 [internal_api.py:execute():325] {"errors":[{"message":"run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-17 21:37:33,594 INFO    WriterThread:15321 [datastore.py:close():298] close: /home/zhizhuo/Creative_Machines_Lab/knolling_bot/train_multi_knolling_zzz/wandb/run-20231017_213446-wv7rm33y/run-wv7rm33y.wandb
2023-10-17 21:37:33,955 DEBUG   HandlerThread:15321 [handler.py:handle_request():144] handle_request: keepalive
2023-10-17 21:37:33,955 INFO    HandlerThread:15321 [handler.py:finish():854] shutting down handler
2023-10-17 21:37:33,956 INFO    HandlerThread:15321 [system_monitor.py:finish():190] Stopping system monitor
2023-10-17 21:37:33,958 DEBUG   SystemMonitor:15321 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-10-17 21:37:33,958 DEBUG   SystemMonitor:15321 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-10-17 21:37:33,964 INFO    HandlerThread:15321 [interfaces.py:finish():202] Joined cpu monitor
2023-10-17 21:37:33,966 INFO    HandlerThread:15321 [interfaces.py:finish():202] Joined disk monitor
2023-10-17 21:37:33,998 INFO    HandlerThread:15321 [interfaces.py:finish():202] Joined gpu monitor
2023-10-17 21:37:33,998 INFO    HandlerThread:15321 [interfaces.py:finish():202] Joined memory monitor
2023-10-17 21:37:33,998 INFO    HandlerThread:15321 [interfaces.py:finish():202] Joined network monitor
2023-10-17 21:37:33,999 ERROR   StreamThr :15321 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1822, in upsert_run
    response = self.gql(
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 293, in gql
    ret = self._retry_gql(
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 321, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 527, in debounce
    self._maybe_update_config(always=final)
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 504, in _maybe_update_config
    self._debounce_config()
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 533, in _debounce_config
    self._api.upsert_run(
  File "/home/zhizhuo/anaconda3/envs/knolling/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run zhizhuo_team/knolling_multi/wv7rm33y was previously created and deleted; try a new run name (Error 409: Conflict)
